server:
  port: 8081
spring:
  application:
    name: crawler-8188
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: ybj
  redis:
    host: 10.130.84.109
    port: 4021
    database: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接，默认值也是0
        min-idle: 8
        # 连接池中的最大空闲连接，默认值也是0
        max-idle: 500
        # 连接池最大连接数
        max-active: 2000
        # 最长等待时间 ms
        max-wait: 100000
    timeout: 100000


#配置 elasticSearch的 url（已过失，过会再改）
  elasticsearch:
    jest:
      uris: http://127.0.0.1:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: crawler-8188
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath:com/ybj/crawler/mapping/*.xml
  type-aliases-package: com.ybj.crawler.model

