server:
  port: 8081

spring:
  mail:
    host: smtp.qq.com
    username: 1793870688@qq.com
    password: naxrczzcyytxgaed
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  datasource:
    username: payment
    password: 6qpxxKxZxY
    url: jdbc:mysql://10.98.32.160:6301/payment_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  file:
    name: logback-crawler.log
    path: ./


