spring:
  mail:
    host: smtp.qq.com
    username: 1793870688@qq.com
    password: naxrczzcyytxgaed
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  datasource:
    username: yuanbaojian
    password: 312ybj
    url: jdbc:mysql://yuanbaojian.xyz:3306/helloWorld?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  file:
    name: logback-crawler.log
    path: ./
