eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: zull-8083
    prefer-ip-address: true

spring:
  application:
    name: zull-8083


zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: dept-8081
    api-b:
      path: /api-b/**
      serviceId: service-feign
server:
  port: 8083