server:
  port: 8187

spring:
  application:
    name: es-8187
  datasource:
    username: test
    password: tezign
    url: jdbc:mysql://10.80.82.13:3306/tenant_manager?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 10.172.161.123
    port: 6389
    password: SSVFDKBJNDFNJ@rfgvf3244
    jedis:
      pool:
        # 连接池中的最小空闲连接，默认值也是0
        min-idle: 8
        # 连接池中的最大空闲连接，默认值也是0
        max-idle: 500
        # 连接池最大连接数
        max-active: 2000
        # 最长等待时间 ms
        max-wait: 100000
    timeout: 100000

  elasticsearch:
    rest:
      uris: http://es-cn-zvp29oayp001mbgk5.elasticsearch.aliyuncs.com:9200
      username: elastic
      password: CwWkTuF1AY14HA3OTo66






#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300



  #eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: es-8187
    prefer-ip-address: true


itl:
  es:
    cluster-nodes: http://es-cn-mp91mb9ff000j5bde.elasticsearch.aliyuncs.com:9200
    cluster-name: elastic
    security-user: CwWkTuF1AY14HA3OTo66

mybatis-plus:
  mapper-locations: classpath:com/ybj/auth/mapping/*.xml , classpath:com/ybj/crawler/mapping/*.xml
  type-aliases-package: com.ybj.auth.model,  com.ybj.crawler.model

