server:
  port: 8191
  tomcat:
    uri-encoding: UTF-8
    max-connections: 200000
spring:
  application:
    name: mysqlStudy
  mail:
    username:  no-reply@ubras.com.cn
    password: B1yue@
    host: smtp.exmail.qq.com
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          port: 465
          auth: true
          starttls:
            enable: true
            required: true


  profiles:
    active: prod
#  redis:
#    host: yuanbaojian.xyz
#    port: 6379
#    password: 312ybj
#    database: 0
#    jedis:
#      pool:
#        # 连接池中的最小空闲连接，默认值也是0
#        min-idle: 8
#        # 连接池中的最大空闲连接，默认值也是0
#        max-idle: 500
#        # 连接池最大连接数
#        max-active: 2000
#        # 最长等待时间 ms
#        max-wait: 100000
#    timeout: 100000



mybatis-plus:
  mapper-locations: classpath:com/ybj/mysql/mapping/*.xml
  type-aliases-package: com.ybj.redPacket.model

  instance:
    instance-id: mysqlStudy
    prefer-ip-address: true