
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mysql_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
          username: root
          password: 312yuanbaojian
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://localhost:3306/t1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
          username: root
          password: 312yuanbaojian
          driver-class-name: com.mysql.jdbc.Driver