server:
  port: 8339
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: user-8186
    prefer-ip-address: true

spring:
  application:
    name: user-8186

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mqadmin
    password: admin
    publisher-returns: true
    publisher-confirm-type: simple
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 4
  mail:
    host: smtp.qq.com
    username: 1793870688@qq.com
    password: naxrczzcyytxgaed
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000

  datasource:
    username: yuanbaojian
    password: 312ybj
    url: jdbc:mysql://yuanbaojian.xyz:3306/helloWorld?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: yuanbaojian.xyz
    port: 6379
    password: 312ybj
    database: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接，默认值也是0
        min-idle: 8
        # 连接池中的最大空闲连接，默认值也是0
        max-idle: 500
        # 连接池最大连接数
        max-active: 2000
        # 最长等待时间 ms
        max-wait: 100000
    timeout: 100000
