spring:
  datasource:
    username: root
    password: 312yuanbaojian
    url: jdbc:mysql://localhost:3306/mysql_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
