spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: MysqlStudy
    password: 312ybj
    url: jdbc:p6spy:mysql://yuanbaojian.xyz:3306/MysqlStudy
    maxActive: 10000
    initialSize: 100
    hikari:
      connection-timeout: 10000
