
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: dept-provider-8081
    prefer-ip-address: true

spring:
  application:
    name: dept-8081

info:
  app.name: cloud
  company.name: ybj
  build.artifactId: $project.artifactId$
  build.version: $project.version$

server:
  port: 8081