vms_channel_wait_message

  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `message_data` text COLLATE utf8mb4_unicode_ci COMMENT '消息内容',
  `title` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '消息标题',
  `dispose_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '处理状态（0：未处理，1：正在处理，2：处理完成）',
  `has_read` tinyint(1) DEFAULT NULL COMMENT '是否已读',
  `user_id` bigint(20) DEFAULT NULL COMMENT '用户id',
  `top_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '置顶状态（0：否，1：是）',
  `expires_time` datetime DEFAULT NULL COMMENT '过期时间',
  `template_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '模板code',
  `business_id` bigint(20) DEFAULT NULL COMMENT '业务id',
  `jump_url` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '跳转地址',
  `business_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '业务code',
  `model_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '模块code',
  `action_code` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '动作code',
  `type_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '待办类型',
  `urgent_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '紧急程度',
  `important_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '重要程度',
  `change_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '由“待处理”变成“已处理”状态触发事件',
  `logo_id` bigint(20) DEFAULT NULL COMMENT '图片id',
  `sort` bigint(20) DEFAULT NULL COMMENT '排序号',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `create_user` bigint(20) DEFAULT NULL COMMENT '创建人',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `update_user` bigint(20) DEFAULT NULL COMMENT '更新人',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除（0：未删除，1：已删除）',
