server:
  port: 8084

spring:
  application:
    name: gateWay-8084
  redis:
    host: yuanbaojian.xyz
    port: 6379
    password: 312ybj
    database: 0
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 100000
    timeout: 100000
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-8085
          uri: lb://auth-8085
          predicates:
          - Path=/auth/**, /menu/**, /user/**
        - id: dept-8081
          uri: lb://dept-8081
          predicates:
          - Path=/dept/**
        - id: crawler-8188
          uri: lb://crawler-8188
          predicates:
          - Path=/bus/**, /folder/**, /IpBean/**
        - id: redPacket_router
          uri: lb://redPacket
          predicates:
          - Path=/redPacket/**, /transaction/**, /userRedPacket/**
        - id: user_router
          uri: lb://user-8186
          predicates:
          - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: auth-8085
    prefer-ip-address: true

gate:
  ignore:
    startWith: /static,/auth

logging:
  level:
    com.ybj.gateWay.gateWay: debug




